stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-jdk-7
      shellScript: echo hello world
- name: 质量测试
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: pwd
notification: {}
